name: Ubuntu Linux

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Who I?
      run: whoami
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -O ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken 2fYlJncfW2vnwcJQXAmukOdmSBC_2ZSjT6d9QiTLehHFpY8Dt
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable SSH
      run: sudo ufw allow 22
    - name: download passwd
      run: git clone https://github.com/BROILYA091/rdp
    - name: Copy passwd
      run: mv rdp/passwd.sh passwd.sh
    - name: Run passwd
      run: sudo sh passwd.sh
    - name: Script VNC server copy
      run: mv rdp/vnc2.sh vnc.sh
    - name: Start VNC server script
      run: sh vnc.sh
    - name: Move workos_filesystem
      run: mv rdp/mint.zip mint.zip
    - name: Extract workos_filesystem
      run: unzip mint.zip
    - name: Start VNC
      run: vncserver -rfbport 5901 -localhost no
    - name: Create Tunnel
      run: ./ngrok tcp 5901
