name: Ubuntu Linux

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -O ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable SSH
      run: sudo ufw allow 22
    - name: Create Tunnel
      run: ./ngrok tcp 22
